name: Backwards Compatibility Tests NeuralSearch
on:
  push:
    branches:
      - "*"
      - "feature/**"
  pull_request:
    branches:
      - "*"
      - "feature/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  Restart-Upgrade-BWCTests-NeuralSearch:
    strategy:
      matrix:
        java: [21, 25]
        os: [ubuntu-latest]
        bwc_version : ["3.6.0"]
        opensearch_version : ["3.7.0-SNAPSHOT"]

    name: NeuralSearch Restart-Upgrade BWC Tests
    runs-on: ${{ matrix.os }}
    env:
      BWC_VERSION_RESTART_UPGRADE: ${{ matrix.bwc_version }}

    steps:
      - name: Checkout neural-search
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - uses: ./.github/actions/clean-up-disk
        if: false # Disable (not using OpenSearch runner)

      - name: Run NeuralSearch Restart-Upgrade BWC Tests from BWCVersion-${{ matrix.bwc_version }} to OpenSearch Version-${{ matrix.opensearch_version }} on ${{matrix.os}}
        run: ./gradlew :qa:restart-upgrade:testAgainstNewCluster --parallel -D'tests.bwc.version=${{ matrix.bwc_version }}'

  Rolling-Upgrade-BWCTests-NeuralSearch:
    strategy:
      matrix:
        java: [21, 25]
        os: [ubuntu-latest]
        bwc_version: ["3.6.0"]
        opensearch_version : ["3.7.0-SNAPSHOT"]

    name: NeuralSearch Rolling-Upgrade BWC Tests
    runs-on: ${{ matrix.os }}
    env:
      BWC_VERSION_ROLLING_UPGRADE: ${{ matrix.bwc_version }}

    steps:
      - name: Checkout neural-search
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - uses: ./.github/actions/clean-up-disk
        if: false # Disable (not using OpenSearch runner)

      - name: Run NeuralSearch Rolling-Upgrade BWC Tests from BWCVersion-${{ matrix.bwc_version }} to OpenSearch Version-${{ matrix.opensearch_version }} on ${{matrix.os}}
        run: ./gradlew :qa:rolling-upgrade:testRollingUpgrade --parallel -D'tests.bwc.version=${{ matrix.bwc_version }}'
